[project]
name = "Aleph"
version = "0.1.0"
description = "Facial Recognition & Identity Discovery System"
classifiers = [
    "Environment :: Console",
    "Topic :: Multimedia :: Graphics :: Capture",
    "Topic :: Scientific/Engineering :: Image Recognition",
]
authors = [{ name = "Kasper Jønsson", email = "dkkasjoe@hotmail.com" }]
readme = "README.md"
urls = { Homepage = "https://github.com/kanerix/Aleph" }
requires-python = "~=3.14.0"
dependencies = [
    "ultralytics>=8.3",
    "pillow>=9.1",
    "rawpy>=0.21",
    "pillow-heif>=0.15",
    "httpx>=0.28.1",
    "open-clip-torch>=3.3.0",
    "numpy>=2.0",
    "insightface>=2.0",
    "onnxruntime>=1.30.0",
]

[tool.uv]
default-groups = ["dev", "lint"]

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]
lint = [
    "ruff>=0.7.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ty.environment]
python = "./.venv"
